name: Deploy Rapsodia

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [[ "${{ job.environment }}" == "production" ]]; then
              cd /opt/rapsodia-production
            else
              cd ~/th1er/malebolge/Rainbow
            fi
            git pull origin develop
            pkill http-server
            nohup npx http-server . -p 8081 -c-1 > /dev/null 2>&1 &

      - name: Healthcheck
        run: |
          if [[ "${{ job.environment }}" == "production" ]]; then
            DOMAIN=th1eros.com
          else
            DOMAIN=th1eros.dev
          fi
          curl -f https://rapsodia.$DOMAIN || exit 1